version: "3.7"

services:
  mydb:
    container_name: "data_base_mysql"
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: portal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: qwerty

  